apiVersion: v1
kind: Service
metadata:
  name: springboot-rancher
spec:
  selector:
    app: springboot-rancher
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Porta entre 30000–32767 (pode ser alterada)
